#ifndef Map_H 
#define Map_H
#include <SFML\Graphics.hpp>
#include "const.h"

using namespace sf;

String TileMap[HEIGHT_MAP] = {
	"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
	"wssmssssssssssssssswssssssssssswsswssssssssswsssssssssswssssmssssssssw",
	"wsssssssssssssssssswssssssssssswsswssssssssswwsssmssssswsssssssssssssw",
	"wwwsswwwwwwwwsswwwwwsswwwwssssswsswwwwwwwwssswwwwwwwssswwwwwwssswssssw",
	"wsssswsssssswsswsssssswsswssssswsswsssssswssswsswsswssswsswssssswwsssw",
	"wsssswsssssswsswsssssswsswwwwwwwsswsssssswsswwsswsswssswsswsssssswsssw",
	"wsswwwsswwsswsswsswwwwwsswsssssssswwwwwsswssssssssswsswwsswsssssswsssw",
	"wsswssssswsswsswsswsssssswsssssssswsmswsswsssssssssssssssswwwwwwwwsssw",
	"wsswssssswsswsswsswssssswwsswssssswssswsswsssssswssssssssssssssssssssw",
	"wsswsswwwwsswsswsswwwwsswssswwwwwwwssssssssssssswsswsswsssssssmssssssw",
	"wsswwwwssssswsswsssssssswssswssssssssssssssssssswssssswsswwwwwwwwwwssw",
	"wssmsswssssswsswsssssssswssswsmssssssswsswwwwwwwwssssswsswsssswssswssw",
	"wssssswsswwwwsswwwwssssswssswsssswsssswssssssssssssssswsswsssswssssssw",
	"wssssswsssswsssssssssssswssswwwwwwsssswssssssssssssssswsswsssswssssssw",
	"wsswssssssswsssssssssssswssssssssssssswssswwwwwwwwwwwwwsswsssswssssssw",
	"wsswssssssswsswssswwwwwwwsssssssssssswwssssswsswssssssssswsssswwwwwwww",
	"wsswwwwwwwwwsswsssssssssssswssssssswwwsssssswsswssmsssssswsssssssssssw",
	"wssssssssssssswsssssssssssswwwwwwwwwsssssssswsswssssssssswsssssssssssw",
	"wssssssssssssswsssssswssssssswsssssssssssssswsswwwwssswwwwsswwwwwwwssw",
	"wssssswwwwwwwwwsssssswwwwsssswsssssssssssssswssssssssssssssswssmsswssw",
	"wssssswsssswsswwwwwwwwsswsssswwwwssswwwwwwwwwssssssssssssssswssssswssw",
	"wssssswsssswsssssssssssswsssswsswssswsssssssssssswwwwwwwsswwwsswwwwssw",
	"wssssswwssswsssssssssssswsssswsswssswsssssssssssswssswsssssswsssmssssw",
	"wsswssswssswsssssswssssswsswwwsswssswsssswwwwsssswssswsssssswssssssssw",
	"wsswssswssswwwwwwwwssssswssssssswssswsssswsswwwwwwssswsssssswwwwwwwwww",
	"wsswwwwwssssswssswsssssswssssssswssswsssswssswssswsmswsssssssssssssssw",
	"wsssssssssssswssswsswwwwwssssssswsswwsssswssswssswssswsssssssssssssssw",
	"wsssssmsssssswssswssssswsssssssswsssssssswssswssssssswsssssswsssmssssw",
	"wsssssssssssswssswsssssssssssssswsssssssswssswssssssswwwwwwwwssssssssw",
	"wsssswwwwwwwwwssswsssssssssssssswwwwwwwwwwssswssssssssswsssssssssssssw",
	"wsssswssssssssssswssssswwwwwwwwwwsssssssssssswssssssssswsssssssssssssw",
	"wsmsswssssssssssswssssssssssssssssssssssssssswssssssssswwwwwwwwwwwwwww",
	"wssssssssswsssssssssssssssmssssssssswsssssssssssssswsssssssssssssssssw",
	"wssssssssswssssssssssssssssssssssssswsssssssssssssswsssssssmsssssssssw",
	"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
	};
#endif