#ifndef Map_H 
#define Map_H
#include <SFML\Graphics.hpp>
#include "const.h"

using namespace sf;

String TileMap[HEIGHT_MAP] = {
	"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
	"wssmssssssssmsssssswssssssssssswsswssssssssswsssssssmsswssssmssssssssw",
	"wsssssssssssssssssswssssssssmsswsswssssmsssswwsssmssssswsssssssssssssw",
	"wwwsswwwwwwwwsswwwwwsswwwwssssswsswwwwwwwwssswwwwwwwssswwwwwwssswssssw",
	"wsssswsmsssswsswsssssswsswssssswsswsssssswssswsswsswssswsswssssswwsssw",
	"wsssswssssmswsswsssssswsswwwwwwwsswsssssswsswwsswsswssswsswssmssswsssw",
	"wsswwwsswwsswsswsswwwwwsswsssssssswwwwwsswssssssssswsswwsswsssssswsssw",
	"wsswssssswsswsswsswsssssswsssssssswsmswsswsssmsssssssssssswwwwwwwwsssw",
	"wsswssssswsswsswsswssssswwsswssssswssswsswsssssswssssmsssssssssssssssw",
	"wsswsswwwwsswsswsswwwwsswssswwwwwwwsssssssmssssswsswsswsssssssmssssssw",
	"wsswwwwssssswsswsssssssswssswssssssssssssssssssswssssswsswwwwwwwwwwssw",
	"wssmsswssssswsswsssssssswssswsmssssssswsswwwwwwwwssssswsswsssswssswssw",
	"wssssswsswwwwsswwwwssssswssswsssswsssswsssssssssssmssswsswsssswssmsssw",
	"wssssswsssswsssssssssssswssswwwwwwsssswssssssmsssssssswsswsssswssssssw",
	"wsswssssssswsssssssssssswssssssssssssswssswwwwwwwwwwwwwsswsssswssssssw",
	"wsswssssssswsswssswwwwwwwsssssssssssswwssssswsswssssssssswsssswwwwwwww",
	"wsswwwwwwwwwsswsssssssssssswssssssswwwsssssswsswssmsssssswsssssssssssw",
	"wssssssssssssswsssssssssssswwwwwwwwwssssmssswsswssssssssswsssssssssssw",
	"wssssssssssssswsssssswssssssswsssssssssssssswsswwwwssswwwwsswwwwwwwssw",
	"wssssswwwwwwwwwsssssswwwwsssswssssmssssssssswssmsssssssssssswssmsswssw",
	"wssssswsssswsswwwwwwwwsswsssswwwwssswwwwwwwwwsssssssssmssssswssssswssw",
	"wssmsswsssswsssssssssssswsssswsswssswsssssssssssswwwwwwwsswwwsswwwwssw",
	"wssssswwssswssssmssssssswsssswsswssswsssssssssssswssswsssssswsssmssssw",
	"wsswssswssswsssssswssssswsswwwsswssswsssswwwwsssswssswsssssswssssssssw",
	"wsswssswssswwwwwwwwssssswssssssswssswsssswsswwwwwwssswsssssswwwwwwwwww",
	"wsswwwwwssssswssswsssssswssssssswssswssmswssswssswsmswsssssssssssssssw",
	"wsssssssssssswssswssswwwwssssssswsswwsssswssswssswssswsssssssssssssssw",
	"wsssssmsssssswssswssssswssssmssswsssssssswssswssssssswsssssswsssmssssw",
	"wsssssssssssswssswssssssssmssssswsssssssswssswssssssswwwwwwwwssssssssw",
	"wsssswwwwwwwwwsmswsssssssssssssswwwwwwwwwwssswssssssssswsssssssssssssw",
	"wsssswssssssssssswssssswwwwwwwwwwsssssssssssswssssmsssswsssssssssssssw",
	"wsmsswssssssssssswssssssssssssssssssssssssssswssssssssswwwwwwwwwwwwwww",
	"wssssssssswsssssssssssssssmssssssssswsssssssssssssswssssssssssssmssssw",
	"wssssssssswsssmssssssssssssssssssssswsssssssssssssswsssssssmsssssssssw",
	"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
	};
#endif